<a href="https://colab.research.google.com/github/Arurwe/data-science-begin/blob/main/begin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PODSTAWY


In [3]:
import numpy as np

np.__version__

'2.0.2'

In [ ]:
help(np.array)

1D ARRAY

In [5]:
x = np.array([1 ,2, 3])
x

array([1, 2, 3])

In [11]:
print('Dimension:', x.ndim) # WYMIAR TABLICY
print('Shape:', x.shape) # KSZTAŁT
print('Size:', x.size) # WIELKOŚC (LICZBA ELEMENTÓW)
print('Data Type:', x.dtype) # TYP DANYCH

Dimension: 1
Shape: (3,)
Size: 3
Data Type: int64


In [13]:
np.array([2.4 , 4.66, 8 , 9.09]).dtype

dtype('float64')

2D ARRAY

In [16]:
y = np.array([[1, 2], [2, -9], [7, 88]])
print(y)

[[ 1  2]
 [ 2 -9]
 [ 7 88]]


In [17]:
print('Dimension:', y.ndim) # WYMIAR TABLICY
print('Shape:', y.shape) # KSZTAŁT
print('Size:', y.size) # WIELKOŚC (LICZBA ELEMENTÓW)
print('Data Type:', y.dtype) # TYP DANYCH

Dimension: 2
Shape: (3, 2)
Size: 6
Data Type: int64


In [ ]:
x = np.array

3D ARRAY

In [19]:
x = np.array(
    [[[2,5,6],
      [3,5,6]],

     [[2,1,1],
      [4,5,8]],
     ]
)

In [20]:
print(x)

[[[2 5 6]
  [3 5 6]]

 [[2 1 1]
  [4 5 8]]]


In [21]:
print('Dimension:', x.ndim) # WYMIAR TABLICY
print('Shape:', x.shape) # KSZTAŁT
print('Size:', x.size) # WIELKOŚC (LICZBA ELEMENTÓW)
print('Data Type:', x.dtype) # TYP DANYCH

Dimension: 3
Shape: (2, 2, 3)
Size: 12
Data Type: int64


**DATA TYPE**

In [24]:
a = np.array([2,9,19], dtype="complex")

In [25]:
a.dtype

dtype('complex128')

In [26]:
a

array([ 2.+0.j,  9.+0.j, 19.+0.j])

In [28]:
a = np.array([True, False, False])
a.dtype

dtype('bool')

In [32]:
# -127 -> 127
a = np.array([24,120,127], dtype=np.int8)
a.dtype

dtype('int8')

In [35]:
# 0 -> 255
a = np.array([24,120,230], dtype=np.uint8)
a.dtype

dtype('uint8')

**TABLE**

np.zeros tworzy domyslnie type=float

1.   np.zeros - tablice z samymi zerami
2.   ones - tablice z samymi jedynkami
3.   full - tworzy tablice z wartością jaką jej podamy
4.   arange - tworzy tablice z podanego zakresu
5.   linspace - tworzy tablice z równo rozłożonymi wartościami między start a stop




In [37]:

np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [38]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.full(shape=(4,7), fill_value=3, dtype='int')

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [40]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(start=5, stop=100, step=10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [42]:
np.arange(start=5, stop=-98, step=-7, dtype='float')

array([  5.,  -2.,  -9., -16., -23., -30., -37., -44., -51., -58., -65.,
       -72., -79., -86., -93.])

In [45]:
np.linspace(start=2, stop=11, num=11)

array([ 2. ,  2.9,  3.8,  4.7,  5.6,  6.5,  7.4,  8.3,  9.2, 10.1, 11. ])

In [62]:
b = np.arange(15)
b.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

**TABLE OPERATION**

In [63]:
x = np.array([2,4,11,3])
a = np.array([1,-2,13,5])
print(x)
print(a)

[ 2  4 11  3]
[ 1 -2 13  5]


In [64]:
a + x

array([ 3,  2, 24,  8])

In [65]:
x - a

array([ 1,  6, -2, -2])

In [66]:
x * a

array([  2,  -8, 143,  15])

In [67]:
a / x

array([ 0.5       , -0.5       ,  1.18181818,  1.66666667])

In [68]:
x / a

array([ 2.        , -2.        ,  0.84615385,  0.6       ])

In [69]:
a + 3

array([ 4,  1, 16,  8])

In [70]:
x / 2

array([1. , 2. , 5.5, 1.5])

In [71]:
x - 2

array([0, 2, 9, 1])

In [72]:
x // 2


array([1, 2, 5, 1])

In [73]:
x % 3

array([2, 1, 2, 0])

In [74]:
a *2*x

array([  4, -16, 286,  30])

In [75]:
np.add(a,x)

array([ 3,  2, 24,  8])

In [76]:
np.subtract(x,a)

array([ 1,  6, -2, -2])

In [78]:
np.multiply(a,x)

array([  2,  -8, 143,  15])

In [79]:
np.divide(a,x)

array([ 0.5       , -0.5       ,  1.18181818,  1.66666667])

In [82]:
x = np.array([[1 , 3],[-2 ,0]])
y = np.array([[6,0],[-1,2]])
print(x, '\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [81]:
x * y

array([[6, 0],
       [2, 0]])

In [83]:
np.dot(x,y)

array([[  3,   6],
       [-12,   0]])

In [84]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [85]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [86]:
x @ y

array([[  3,   6],
       [-12,   0]])

MACIERZE X oraz Y

1. Operacje matematyczne:
- X + Y   | np.add( X , Y )
- X - Y   | np.subtract( X , Y )
- X // Y  | np.floor_divide( X, Y ) - dzielenie bez reszty
- X / Y   | np.divide( X , Y ) albo np.true_divide( X , Y )- dzielenie
- X * Y   | np.multiply( X , Y ) - mnożenie
- X % Y   | np.mod( X , Y) albo np.remider( X , Y ) - modulo




MNOŻENIE MACIERZY:
1. np.dot(X , Y)
2. X.dot(Y)
3. X @ Y
4. np.matmul ( X , Y ) - nowoczesne np.dot -> to samo co X @ Y (dobrze działa na array 3D)




**GENEROWANIE LICZB PSEUDOLOSOWYCH**

In [88]:
# Ustawienie ziarna losowania
np.random.seed(0)

In [89]:
np.random.randn()

1.764052345967664

In [90]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [92]:
np.random.randn(10, 4)

array([[ 0.3869025 , -0.51080514, -1.18063218, -0.02818223],
       [ 0.42833187,  0.06651722,  0.3024719 , -0.63432209],
       [-0.36274117, -0.67246045, -0.35955316, -0.81314628],
       [-1.7262826 ,  0.17742614, -0.40178094, -1.63019835],
       [ 0.46278226, -0.90729836,  0.0519454 ,  0.72909056],
       [ 0.12898291,  1.13940068, -1.23482582,  0.40234164],
       [-0.68481009, -0.87079715, -0.57884966, -0.31155253],
       [ 0.05616534, -1.16514984,  0.90082649,  0.46566244],
       [-1.53624369,  1.48825219,  1.89588918,  1.17877957],
       [-0.17992484, -1.07075262,  1.05445173, -0.40317695]])

In [93]:
np.random.rand()

0.8811031971111616

In [95]:
np.random.rand(10)

array([0.30157482, 0.66017354, 0.29007761, 0.61801543, 0.4287687 ,
       0.13547406, 0.29828233, 0.56996491, 0.59087276, 0.57432525])

In [96]:
np.random.rand(10,3)

array([[0.65320082, 0.65210327, 0.43141844],
       [0.8965466 , 0.36756187, 0.43586493],
       [0.89192336, 0.80619399, 0.70388858],
       [0.10022689, 0.91948261, 0.7142413 ],
       [0.99884701, 0.1494483 , 0.86812606],
       [0.16249293, 0.61555956, 0.12381998],
       [0.84800823, 0.80731896, 0.56910074],
       [0.4071833 , 0.069167  , 0.69742877],
       [0.45354268, 0.7220556 , 0.86638233],
       [0.97552151, 0.85580334, 0.01171408]])

In [104]:
np.random.randint(12)

2

In [105]:
np.random.randint(low=11, high=344)

99

In [106]:
np.random.randint(low=11, high=344, size=10)

array([ 44, 144, 243, 266,  47, 267, 301, 208, 265,  91])

In [110]:
np.random.choice([4,2,1,3,5])

np.int64(4)

In [111]:
np.random.choice(['aaa', 'bbb', 'ccc'])

np.str_('aaa')

In [115]:
d = np.arange(10)
np.random.shuffle(d)
d

array([0, 8, 9, 1, 5, 3, 4, 2, 7, 6])

**PODSTAWOWE FUNKCJE**

In [116]:
# STAŁA EULERA |  e
np.exp(1)

np.float64(2.718281828459045)

In [117]:
np.exp(2)

np.float64(7.38905609893065)

In [118]:
np.sqrt(9)

np.float64(3.0)

In [119]:
np.all([2, 5, 1])

np.True_

In [129]:
np.all([2, 1,0 ])

np.False_

In [134]:
np.any([0, 1 , 0])

np.True_

In [136]:
bool(0)

False

In [151]:
a = np.random.rand(5)
a

array([0.22921932, 0.8815854 , 0.90442498, 0.6457846 , 0.32468297])

In [139]:
np.argmax(a)

np.int64(3)

In [140]:
a[np.argmax(a)]

np.float64(0.9064180870601711)

In [142]:
a.argmin()

np.int64(4)

In [143]:
np.argsort(a)

array([4, 2, 1, 0, 3])

In [150]:
np.max(a)


np.float64(0.9064180870601711)

In [145]:
np.min(a)

np.float64(0.1372204200971946)

In [146]:
np.mean(a)

np.float64(0.5367694499407522)

In [147]:
np.median(a)

np.float64(0.46949718309117094)

In [148]:
np.std(a)

np.float64(0.260378429398107)

np.random - do losowania
np.random.randn() - losowanie
np.random.rand() -
np.random.

- np.exp() - liczba eulera - e
- np.sqrt(LICZBA) - pierwastek
- np.all(X) - zwraca True / False = True jeśli wszystkie dane w tablicy są TRUE
- np.any(X) - zwraca True / False = True jeśli jaka kolwiek dana jest TRUE
- np.argmin(X) - index min wartosci
- np.min(X) - min wartość
- np.max(X) - max wartość
- np.argmax(X) - index max wartosci
- np.mean(X) - średnia
- np.median(X) - mediana
- np.std(X) - odchylenie standardowe

**INDEXOWANIE , WYCINANIE**

In [154]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [155]:
# a[index]
# a[start : stop]
# a[:stop]
# a[start:]

In [156]:
a[2]

np.int64(2)

In [157]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [158]:
a[:2]

array([0, 1])

In [160]:
a[[0,4,6]]

array([0, 4, 6])

In [161]:
a[-7]

np.int64(13)

In [162]:
a[[-8,2,-1]]

array([12,  2, 19])

In [163]:
a[13:16]

array([13, 14, 15])

In [166]:
a = a.reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [167]:
a[0]

array([0, 1, 2, 3, 4])

In [168]:
a[[1]]

array([[5, 6, 7, 8, 9]])

In [169]:
a[:,0]

array([ 0,  5, 10, 15])

In [170]:
a[1,1]

np.int64(6)

In [171]:
a[1,:]

array([5, 6, 7, 8, 9])

In [172]:
a[:,2]

array([ 2,  7, 12, 17])

In [177]:
a[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [178]:
a[1,2] = 5

In [179]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  5,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**ITERACJA PO TABLICY**

In [181]:
for i in a:
  print(i)

[0 1 2 3 4]
[5 6 5 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [186]:
for i in a:
  print(i[:2])

[0 1]
[5 6]
[10 11]
[15 16]


In [185]:
for i in a.flat:
  print(i)

0
1
2
3
4
5
6
5
8
9
10
11
12
13
14
15
16
17
18
19


**ZMIANA ROZMARU TABLIC**

In [187]:
a.shape

(4, 5)

In [188]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  5],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [189]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  5,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [190]:
a.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  5, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

**MASKI LOGICZNE**

In [192]:
a = np.arange(start=-10 , stop =10 , step=0.5)

In [193]:
a = a.reshape(10, -1)

In [194]:
a

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [195]:
a > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [201]:
a[a>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [203]:
np.bitwise_and(a > -5, a < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [204]:
a[np.bitwise_and(a > -5, a < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [205]:
np.bitwise_or(a < -5, a > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])